import JSZip from 'jszip';
import slugify from 'slugify';

export async function generateConstitutionZip(
  sessionName: string,
  constitutionMarkdown: string,
  version: number
): Promise<Buffer> {
  const zip = new JSZip();
  const safeName = slugify(sessionName, { lower: true, strict: true });

  zip.file(
    `${safeName}-constitution.md`,
    constitutionMarkdown
  );

  zip.file(
    'README.md',
    `# ${sessionName} Constitution

This archive contains the constitution generated by Constitution Builder.

## Files

- \`${safeName}-constitution.md\` — The full constitution document (Markdown)

## Version

- Version: ${version}
- Generated: ${new Date().toISOString().split('T')[0]}

## Usage

This constitution is a living document. To propose amendments:

1. Review the amendment process described in Section 4 (Meta)
2. Follow the decision-making protocols in Section 3 (Protocols)
3. Update the version number and date when changes are adopted

## About

Generated using [Constitution Builder](https://github.com/opencivics/constitution-builder) by OpenCivics Labs.
`
  );

  const buffer = await zip.generateAsync({ type: 'nodebuffer' });
  return buffer;
}
