import { CONSTITUTION_COMPONENTS } from './components';

interface DraftSection {
  component: string;
  title: string;
  content: string;
}

interface AssemblyContext {
  sessionName: string;
  slug: string;
  version: number;
  participantCount: number;
}

export function assembleConstitutionMarkdown(
  sections: DraftSection[],
  context: AssemblyContext
): string {
  const sectionMap = new Map(sections.map((s) => [s.component, s]));
  const date = new Date().toISOString().split('T')[0];

  const lines: string[] = [];

  // Frontmatter
  lines.push('---');
  lines.push(`id: ${context.slug}-constitution`);
  lines.push(`name: ${context.sessionName} Constitution`);
  lines.push(`version: ${context.version}`);
  lines.push(`lastUpdated: ${date}`);
  lines.push(`generatedBy: Constitution Builder`);
  lines.push(`participants: ${context.participantCount}`);
  lines.push('---');
  lines.push('');

  // Title
  lines.push(`# ${context.sessionName} Constitution`);
  lines.push('');

  // Identity
  const identityComponents = CONSTITUTION_COMPONENTS.filter(c => c.section === 'identity');
  if (identityComponents.some(c => sectionMap.has(c.id))) {
    lines.push('## 1. Identity');
    lines.push('');
    for (const comp of identityComponents) {
      const section = sectionMap.get(comp.id);
      if (section) {
        lines.push(`### ${comp.title}`);
        lines.push('');
        lines.push(section.content);
        lines.push('');
      }
    }
  }

  // Structure
  const structureComponents = CONSTITUTION_COMPONENTS.filter(c => c.section === 'structure');
  if (structureComponents.some(c => sectionMap.has(c.id))) {
    lines.push('## 2. Structure');
    lines.push('');
    for (const comp of structureComponents) {
      const section = sectionMap.get(comp.id);
      if (section) {
        lines.push(`### ${comp.title}`);
        lines.push('');
        lines.push(section.content);
        lines.push('');
      }
    }
  }

  // Protocols
  const protocolComponents = CONSTITUTION_COMPONENTS.filter(c => c.section === 'protocols');
  if (protocolComponents.some(c => sectionMap.has(c.id))) {
    lines.push('## 3. Protocols');
    lines.push('');
    for (const comp of protocolComponents) {
      const section = sectionMap.get(comp.id);
      if (section) {
        lines.push(`### ${comp.title}`);
        lines.push('');
        lines.push(section.content);
        lines.push('');
      }
    }
  }

  // Meta
  lines.push('## 4. Meta');
  lines.push('');
  lines.push('### Amendment Process');
  lines.push('');
  lines.push('This constitution is a living document. Amendments may be proposed by any member and require consensus through the established decision-making protocols described in Section 3.');
  lines.push('');
  lines.push('### Review Cadence');
  lines.push('');
  lines.push('This constitution should be reviewed annually, or when significant organizational changes occur.');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by Constitution Builder on ${date}. Version ${context.version}.*`);

  return lines.join('\n');
}
